### ISSUE TITLE
Problem with parenthesis and boolean operators ('and'/'or') in c++11

### ISSUE THREAD

**Issue by rodrigoapereira** [bengardner/uncrustify#309]
I found this problem using the operator 'and' or operator 'or' followed by parentheses

Before uncrustify:
```C++
if (1 == 1 and (1 != 2))
```

After uncrustify:
```C++
if (1 == 1 and(1 != 2))
```

Using uncrustify 0.60 (af87b47).

**Comment by bengardner** [comment]
Cannot reproduce.  Possibly because there is no config file.
