### ISSUE TITLE
Inserting space before method call ([[a alloc]method])

### ISSUE THREAD

**Issue by MartinMoizard** [bengardner/uncrustify#317]
Hi,

I would like to change `[[a alloc]method]` to `[[a alloc] method]`. I cannot find a rule to do that. Am I missing something?

Thanks a lot

**Comment by studymike** [comment]
I think that would be `sp_after_oc_msg_receiver`

**Comment by bengardner** [comment]
I'll assume this is resolved.

**Comment by jaybowong** [comment]
@studymike THANKS!
