### ISSUE TITLE
<noformatting>

### ISSUE THREAD

**Issue by Keepun** [bengardner/uncrustify#320]
Needed
```java
int number = 7;
// <noformatting>
if   (  3 ==  true)
   {
 return 6;
// </noformatting>
}
```
for the problem area code.

The entire file is processed completely, but when saving to replace the string between &lt;noformatting&gt; and &lt;/noformatting&gt; to the original.

**Comment by bengardner** [comment]
Try running uncrustify without arguments and look for this part:

```
Note: Use comments containing ' *INDENT-OFF*' and ' *INDENT-ON*' to disable
      processing of parts of the source file (these can be overridden with 
      enable_processing_cmt and disable_processing_cmt.
```
