### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by dirk-thomas** [bengardner/uncrustify#421]
The latest release (0.61) is already more than one year old. A lot of important fixes and great enhancement has been implemented since then. It would be nice to make them available to users which use a released version or package from a Linux distribution. Thank you.

**Comment by dirk-thomas** [comment]
Since the feature freeze and debian import freeze for Ubuntu 16.04 is approaching (Feb. 18th) it would be really important to release a new version to make sure the upcoming LTS doesn't ship with a very outdated version of uncrustify.

**Comment by bengardner** [comment]
I'll try to spin a release soon.

**Comment by dirk-thomas** [comment]
*ping* :wink: This is getting really close to the deadline which is in ten days. And this needs to go through the whole pipeline of being released, packaged into Debian and imported into Ubuntu.

**Comment by dirk-thomas** [comment]
It looks like this has been done already: 5987f2223f16b993dbece1360363eef9515fe5e8
