### ISSUE TITLE
Failing to beautify C# with atom-beautify

### ISSUE THREAD

**Issue by philhudson91** [bengardner/uncrustify#425]
On OSX El Capitan

Note: 

`Error: Parsing: /var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3 as language CS`

Failing to beautify C# - stacktrace:

Parsing: /var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3 as language CS
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:19 Garbage in col 12: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:31 Garbage in col 38: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:31 Garbage in col 40: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:32 Garbage in col 27: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:32 Garbage in col 33: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:33 Garbage in col 27: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:33 Garbage in col 33: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:33 Garbage in col 46: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:33 Garbage in col 65: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:35 Garbage in col 27: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:35 Garbage in col 33: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:37 Garbage in col 18: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:37 Garbage in col 38: 2013
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:37 Garbage in col 53: 201d
Hide Stack Trace
Error: Parsing: /var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3 as language CS
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:19 Garbage in col 12: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:31 Garbage in col 38: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:31 Garbage in col 40: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:32 Garbage in col 27: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:32 Garbage in col 33: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:33 Garbage in col 27: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:33 Garbage in col 33: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:33 Garbage in col 46: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:33 Garbage in col 65: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:35 Garbage in col 27: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:35 Garbage in col 33: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:37 Garbage in col 18: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:37 Garbage in col 38: 2013
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:37 Garbage in col 53: 201d
at /Users/philhudson/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:258:27
at tryCatcher (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
at Promise._settlePromiseFromHandler (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:507:31)
at Promise._settlePromiseAt (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:581:18)
at Promise._settlePromises (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:697:14)
at Async._drainQueue (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:123:16)
at Async._drainQueues (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:133:10)
at MutationObserver.Async.drainQueues (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:15:14)
at process._tickCallback (node.js:368:9)

**Comment by addonszz** [comment]
Post also the source and debug results. Example:
Uncrustify.exe -c amxmodx.cfg -f new.sma -p debug.txt
[new.txt](https://github.com/bengardner/uncrustify/files/97537/new.txt)
[debug.txt](https://github.com/bengardner/uncrustify/files/97535/debug.txt)

**Comment by bengardner** [comment]
Looks like you edited your source in MS Word and have all sorts of unicode pollution.
Does it even compile?  I'm guessing not.
