### ISSUE TITLE
Cannot use "~" in uncrustify config path

### ISSUE THREAD

**Issue by JohannesNeumann** [bengardner/uncrustify#426]
I just installed atom-beautify and tried to use a custom uncrustify config located in my home directory. Typing "~/uncrustify.cfg" into "Settings panel" -> "C-Config Path" results in an error message that
projectDirectory/~/uncrustify.cfg" is not found.

Apparently this is an error related to uncrustify itself and not the atom-beautify extension.

Platform: OSX 10.11

**Comment by mgrebenets** [comment]
To me looks like Atom extension problem.
It didn't resolve `~` into `/Users/<yourusername>`.
Have you tried to use `${HOME}` instead of `~` in config?
And of course you can just use `/Users/<yourusername>/uncrustify.cfg`, I don't see what benefits you would get from using `~` there.

**Comment by bengardner** [comment]
Doesn't sound like an issue with Uncrustify.
